import { BlogItem } from '@/common/types/blog'

const BLOG_USER = {
  name: 'Wawan Setiawan',
  username: 'wawansetiawan',
  twitter_username: null,
  github_username: 'wawanneutron',
  user_id: 177502,
  website_url: 'https://hellowawansetiawan.my.id',
  profile_image: 'https://res.cloudinary.com/dqenciruv/image/upload/v1775026417/open-to-work_rciym3.jpg',
  profile_image_90: 'https://res.cloudinary.com/dqenciruv/image/upload/v1775026417/open-to-work_rciym3.jpg'
}

export const BLOGS: BlogItem[] = [
  {
    type_of: 'article',
    id: 1,
    title: '7 Pola Arsitektur Frontend yang Bikin Project Tetap Rapi Saat Tim Membesar',
    description:
      'Bahas folder structure, separation of concerns, dan strategi komponen reusable supaya codebase frontend tetap enak di-maintain walau fitur terus bertambah.',
    published: true,
    published_at: '2026-03-12T08:00:00.000Z',
    slug: '7-pola-arsitektur-frontend-project-tetap-rapi',
    path: '/7-pola-arsitektur-frontend-project-tetap-rapi',
    url: 'https://hellowawansetiawan.my.id/blog/7-pola-arsitektur-frontend-project-tetap-rapi',
    comments_count: 14,
    public_reactions_count: 128,
    page_views_count: 3421,
    published_timestamp: '2026-03-12T08:00:00.000Z',
    body_markdown: 'Konten lengkap membahas modular architecture, feature-first foldering, dan standar naming.',
    positive_reactions_count: 112,
    cover_image: 'https://res.cloudinary.com/dqenciruv/image/upload/q_auto/f_auto/v1775056757/article-1_muvsw6.avif',
    tag_list: ['Frontend', 'Architecture', 'React'],
    canonical_url: 'https://hellowawansetiawan.my.id/blog/7-pola-arsitektur-frontend-project-tetap-rapi',
    reading_time_minutes: 8,
    user: BLOG_USER,
    db_views_count: 3421,
    total_views_count: 3421,
    collection_id: 0,
    created_at: '2026-03-12T08:00:00.000Z'
  },
  {
    type_of: 'article',
    id: 2,
    title: 'Nuxt vs Next di Dunia Nyata: Kapan Pilih yang Mana?',
    description:
      'Bukan sekadar perbandingan fitur. Artikel ini fokus ke studi kasus: SEO, time-to-market, skill tim, hingga biaya maintenance jangka panjang.',
    published: true,
    published_at: '2026-03-05T08:00:00.000Z',
    slug: 'nuxt-vs-next-di-dunia-nyata',
    path: '/nuxt-vs-next-di-dunia-nyata',
    url: 'https://hellowawansetiawan.my.id/blog/nuxt-vs-next-di-dunia-nyata',
    comments_count: 9,
    public_reactions_count: 96,
    page_views_count: 2764,
    published_timestamp: '2026-03-05T08:00:00.000Z',
    body_markdown: 'Perbandingan ekosistem, DX, SSR behavior, dan deployment workflow untuk tim produk.',
    positive_reactions_count: 87,
    cover_image: 'https://res.cloudinary.com/dqenciruv/image/upload/q_auto/f_auto/v1775056757/article-2_qlpt3e.avif',
    tag_list: ['Nuxt', 'Next.js', 'JavaScript'],
    canonical_url: 'https://hellowawansetiawan.my.id/blog/nuxt-vs-next-di-dunia-nyata',
    reading_time_minutes: 7,
    user: BLOG_USER,
    db_views_count: 2764,
    total_views_count: 2764,
    collection_id: 0,
    created_at: '2026-03-05T08:00:00.000Z'
  },
  {
    type_of: 'article',
    id: 3,
    title: 'Checklist CI/CD untuk Frontend: Dari Pull Request sampai Production',
    description:
      'Panduan praktis menyiapkan pipeline yang aman: lint, test, build preview, quality gate, dan strategi rollback cepat saat incident.',
    published: true,
    published_at: '2026-02-23T08:00:00.000Z',
    slug: 'checklist-ci-cd-frontend-dari-pr-sampai-production',
    path: '/checklist-ci-cd-frontend-dari-pr-sampai-production',
    url: 'https://hellowawansetiawan.my.id/blog/checklist-ci-cd-frontend-dari-pr-sampai-production',
    comments_count: 11,
    public_reactions_count: 104,
    page_views_count: 3198,
    published_timestamp: '2026-02-23T08:00:00.000Z',
    body_markdown: 'Membahas stage pipeline, caching dependency, dan deploy strategy berbasis branch.',
    positive_reactions_count: 95,
    cover_image: 'https://res.cloudinary.com/dqenciruv/image/upload/q_auto/f_auto/v1775056759/article-3_tpj41d.avif',
    tag_list: ['CI/CD', 'DevOps', 'Frontend'],
    canonical_url: 'https://hellowawansetiawan.my.id/blog/checklist-ci-cd-frontend-dari-pr-sampai-production',
    reading_time_minutes: 9,
    user: BLOG_USER,
    db_views_count: 3198,
    total_views_count: 3198,
    collection_id: 0,
    created_at: '2026-02-23T08:00:00.000Z'
  },
  {
    type_of: 'article',
    id: 4,
    title: 'TypeScript Patterns yang Paling Kepakai di Project Enterprise',
    description:
      'Belajar pakai utility type, discriminated unions, dan contract typing untuk bikin kode lebih aman tanpa bikin development lambat.',
    published: true,
    published_at: '2026-02-15T08:00:00.000Z',
    slug: 'typescript-patterns-paling-kepakai-di-project-enterprise',
    path: '/typescript-patterns-paling-kepakai-di-project-enterprise',
    url: 'https://hellowawansetiawan.my.id/blog/typescript-patterns-paling-kepakai-di-project-enterprise',
    comments_count: 7,
    public_reactions_count: 81,
    page_views_count: 2417,
    published_timestamp: '2026-02-15T08:00:00.000Z',
    body_markdown: 'Implementasi practical generics, mapped types, dan API response typing.',
    positive_reactions_count: 76,
    cover_image: 'https://res.cloudinary.com/dqenciruv/image/upload/q_auto/f_auto/v1775056757/article-4_xmcnsx.avif',
    tag_list: ['TypeScript', 'Best Practice', 'Frontend'],
    canonical_url: 'https://hellowawansetiawan.my.id/blog/typescript-patterns-paling-kepakai-di-project-enterprise',
    reading_time_minutes: 6,
    user: BLOG_USER,
    db_views_count: 2417,
    total_views_count: 2417,
    collection_id: 0,
    created_at: '2026-02-15T08:00:00.000Z'
  }
]
